# Tensor Flow Basics

## Basic syntax

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("world!")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'Hello world!'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4), 10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [21]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [22]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [23]:
my_ops = [ const, fill_mat, myzeros, myones, myrandn, myrandu ]

In [24]:
sess = tf.InteractiveSession()

In [27]:
for op in my_ops:
    # These two are equivalent
    print(op.eval()
    # print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.6058051   1.4479202  -0.98891199  0.65501261]
 [-0.46227324  0.10655061 -0.18133736 -0.93785942]
 [ 0.19205877  0.69734663  0.71280676 -0.82113409]
 [ 1.15355563  0.0197337   0.89696366  0.26767954]]


[[ 0.84397161  0.95273161  0.62809289  0.51879549]
 [ 0.02782416  0.91645813  0.21072745  0.31647003]
 [ 0.93952656  0.34791672  0.06181204  0.92713046]
 [ 0.4927386   0.03523755  0.48267162  0.57501066]]




In [28]:
a = tf.constant([ [1,2],
                  [3, 4 ]])

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b = tf.constant([ [10], [100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a, b)

In [33]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [81]:
result.eval()

AttributeError: 'numpy.int32' object has no attribute 'eval'

## Graphs

Sets of connected nodes, each is an operation with possible inputs that can supply outputs

Usually we construct a graph and then execute it.

In [35]:
n1 = tf.constant(1)

In [36]:
n2 = tf.constant(2)

In [37]:
n3 = n1 + n2

In [38]:
with tf.Session() as sess:
    result = sess.run(n3)

In [42]:
result

3

In [43]:
print(tf.get_default_graph())

In [44]:
g = tf.Graph()

In [45]:
print(g)

In [46]:
graph_one = tf.get_default_graph()

In [48]:
graph_two = tf.Graph()

In [49]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [50]:
print(graph_two is tf.get_default_graph())

False


In [51]:
print(graph_one is tf.get_default_graph())

True


## Variables and Placeholders

Variables are the parameters that TF tunes when training a model. 

They need to be initialized

Placeholders are initially empty and represent the actual training data. 

They need to have an expected data type.

In [52]:
sess = tf.InteractiveSession()

In [53]:
my_tensor = tf.random_uniform((4,4), 0, 1)

In [54]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [55]:
my_var = tf.Variable(initial_value=my_tensor)

In [56]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [58]:
# Fails the first time because the variable is not initialized yet
#sess.run(my_var)

In [59]:
init = tf.global_variables_initializer()

In [60]:
sess.run(init)

In [61]:
sess.run(my_var)

array([[ 0.13831782,  0.53666162,  0.08722579,  0.52584398],
       [ 0.55689859,  0.25480235,  0.64985859,  0.5821923 ],
       [ 0.50220096,  0.78230798,  0.94816017,  0.3716259 ],
       [ 0.55551553,  0.6666249 ,  0.21914923,  0.27512443]], dtype=float32)

In [62]:
ph = tf.placeholder(tf.float32)

## First TF Neural Network

build graph
initialize the session
feed data in and get output

add the cost function to optimize the parameters

In [63]:
import numpy as np

In [66]:
np.random.seed(101)
tf.set_random_seed(101)

In [67]:
rand_a = np.random.uniform(0, 100, (5, 5))

In [68]:
rand_a

array([[ 51.63986277,  57.06675869,   2.84742265,  17.15216562,
         68.52769817],
       [ 83.38968626,  30.69662197,  89.36130797,  72.15438618,
         18.99389542],
       [ 55.42275911,  35.2131954 ,  18.18924027,  78.56017619,
         96.54832224],
       [ 23.23536618,   8.35614337,  60.35484223,  72.89927573,
         27.62388285],
       [ 68.53063288,  51.78674742,   4.84845374,  13.78692376,
         18.69674261]])

In [69]:
rand_b = np.random.uniform(0, 100, (5, 1))

In [70]:
rand_b

array([[ 99.43179012],
       [ 52.06653967],
       [ 57.87895355],
       [ 73.48190583],
       [ 54.19617722]])

In [71]:
a = tf.placeholder(tf.float32)

In [72]:
b = tf.placeholder(tf.float32)

In [73]:
add_op = a + b

In [74]:
mul_op = a * b

In [80]:
with tf.Session() as sess:
    add_result = sess.run(add_op, feed_dict={a: rand_a, b: rand_b})
    print(add_result)
    print('\n')
    mult_result = sess.run(mul_op, feed_dict={a: rand_a, b: rand_b})
    print(mult_result)

[[ 151.07165527  156.49855042  102.27921295  116.58396149  167.95948792]
 [ 135.45622253   82.76316071  141.42784119  124.22093201   71.06043243]
 [ 113.30171204   93.09214783   76.06819153  136.43911743  154.42727661]
 [  96.7172699    81.83804321  133.83674622  146.38117981  101.10578918]
 [ 122.72680664  105.98292542   59.04463196   67.98310089   72.89292145]]


[[ 5134.64404297  5674.25         283.12432861  1705.47070312
   6813.83154297]
 [ 4341.8125      1598.26696777  4652.73388672  3756.8293457    988.9463501 ]
 [ 3207.8112793   2038.10290527  1052.77416992  4546.98046875
   5588.11572266]
 [ 1707.37902832   614.02526855  4434.98876953  5356.77734375
   2029.85546875]
 [ 3714.09838867  2806.64379883   262.76763916   747.19854736
   1013.29199219]]
