# Reinforcement Learning

## Useful resources: 

Wikipedia: https://en.wikipedia.org/wiki/Reinforcement_learning

Keras: https://github.com/matthiasplappert/keras-rl

RL Algorithm Repository: https://github.com/dennybritz/reinforcement-learning

Berkeley course: http://rll.berkeley.edu/deeprlcourse/

Articles: https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0


## OpenAI Gym

Official documentation: gym.openai.com

Available environments: http://gym.openai.com/envs/#classic_control

## Set-up

- Use editor or IDE and command line.
- Code in .py, do not use Notebooks


In [1]:
import gym
print("It WORKS")

It WORKS


## Gym Observations

A the `step` function returns the following values: 

- observation: The state of the environment.
- reward: The amount of reward achieved by the previous action. The number may vary depending on the environment. 
- done: Boolean indicating whether the environment needs to be reset.
- info: Dictionary with diagnostic information, used for debugging.


In [21]:
import gym
import time

In [23]:
env = gym.make('CartPole-v0')
print('Initial Observation')
observation = env.reset()
print(observation)
print('\n')
for _ in range(10):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print("Performed One Random Action")
    print('observation')
    print(observation)
    print('reward')
    print(reward)
    print('done')
    print(done)
    print('info')
    print(info)
    print('\n')
    time.sleep(0.5)
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Initial Observation
[ 0.02038799  0.01437287  0.02857049  0.01362293]


Performed One Random Action
observation
[ 0.02067544  0.20907368  0.02884295 -0.26991052]
reward
1.0
done
False
info
{}


Performed One Random Action
observation
[ 0.02485692  0.40377241  0.02344473 -0.5533585 ]
reward
1.0
done
False
info
{}


Performed One Random Action
observation
[ 0.03293237  0.59855742  0.01237756 -0.8385636 ]
reward
1.0
done
False
info
{}


Performed One Random Action
observation
[ 0.04490351  0.79350819 -0.00439371 -1.12732843]
reward
1.0
done
False
info
{}


Performed One Random Action
observation
[ 0.06077368  0.59844407 -0.02694028 -0.83602684]
reward
1.0
done
False
info
{}


Performed One Random Action
observation
[ 0.07274256  0.79392345 -0.04366081 -1.13705899]
reward
1.0
done
False
info
{}


Performed One Random Action
observation
[ 0.08862103  0.59939893 -0.06640199 -0.85838247]
reward


In [27]:
import gym
env = gym.make('CartPole-v0')
# Documentation: https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L40
env.action_space

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


Discrete(2)

In [28]:
env.observation_space

Box(4,)

In [31]:
import gym 
env = gym.make('CartPole-v0')
observation = env.reset()

for t in range(1000):
    env.render()
    cart_pos, cart_vel, pole_ang, ang_vel = observation
    action = int(pole_ang > 0)
    observation, rewared, done, info = env.step(action)
    if (done): 
        break
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
